import type { FormaElement, Urn } from "@spacemakerai/element-types"
import type { NotPersistedContainers, SavingResult } from "src/core/elements-saving/result"
import { genericSaveError } from "src/core/elements-saving/result"
import BasicBuildingAPI from "./BasicBuildingAPI"
import { parseUrn } from "src/lib/element/urn"
import type { BufferGeometry } from "three"
import { request } from "src/lib/request"
import type { BasicBuildingElement } from "./lib/types"
import { generateVolume25DCollection } from "./lib/generate-volume25DCollection"
import { gzip } from "pako"
import type { BuildingPieceMesh, VisualizationSettings } from "src/lib/visualizationSettings"
import { calculateEdgesGeometry } from "src/lib/three/geometryUtils"
import type { Selectable, SelectionMode } from "src/core/elements/element-container-derived-data/selectables"
import type { ElementContainer } from "src/core/elements/ElementContainer"
import type { ElementSnapshot } from "src/core/elements/ElementSnapshot"
import { loadPersistedElementsAndChildren } from "src/core/elements-saving/loading"
import { PROJECT_ID } from "src/core/project/project"
import type { ElementSystem } from "src/core/element-systems"
import { NO_OVERRIDE } from "src/core/element-systems"
import { generateAreaStatsSurfaces } from "./area-stats-surfaces"

export default class BasicBuildingElementSystem implements ElementSystem {
  // eslint-disable-next-line @typescript-eslint/require-await
  customFetchVolumeMeshes = async (element: FormaElement): Promise<Map<Urn, BufferGeometry>> => {
    if (!BasicBuildingAPI.isBasicBuilding(element)) return new Map()
    return BasicBuildingAPI.makeBufferGeometryMap(element)
  }

  applyVisualizationSettings_DEPRECATED = (element: FormaElement, visualizationSettings: VisualizationSettings) => {
    if (BasicBuildingAPI.isBasicBuilding(element)) {
      return BasicBuildingAPI.makeBufferGeometryMap(element, visualizationSettings)
    }
    return undefined
  }

  generateUnitMeshes(element: FormaElement): BuildingPieceMesh[] | typeof NO_OVERRIDE {
    if (BasicBuildingAPI.isBasicBuilding(element)) {
      return BasicBuildingAPI.makeUnitMeshes(element)
    }
    if (BasicBuildingAPI.isBasicFloor(element)) {
      return [] // This needs to return empty list, as it overrides the default rendering of volumeMesh.
    }
    return NO_OVERRIDE
  }

  generateEdgeOutlines = (element: FormaElement) => {
    if (BasicBuildingAPI.isBasicBuilding(element)) {
      return BasicBuildingAPI.makeOutlines(element.representations.__INTERNAL__.data, element.urn).outlines
    }
    if (BasicBuildingAPI.isBasicFloor(element)) {
      // Outlines for the floor elements will be generated by the parent element (the building
      // element), so we don't want outlines to be produced by the floor elements too
      return new Float32Array()
    }
    return
  }

  generateSvgOutlines = (element: FormaElement) => {
    return this.generateEdgeOutlines(element)
  }

  generateSelectables = (
    container: ElementContainer,
  ): { selectionMode: SelectionMode; selectables: Selectable[] } | undefined => {
    const element = container.element
    if (!BasicBuildingAPI.isBasicBuilding(element) || !element.children) return
    const hitboxes = BasicBuildingAPI.makeBuildingHitboxes(element)
    const buildingOutlines = BasicBuildingAPI.makeOutlines(element.representations.__INTERNAL__.data, element.urn)
    const roofSelectable: Selectable = {
      target: { type: "element" },
      selectable3d: {
        hitbox: hitboxes[element.urn]?.[0],
        outlines: buildingOutlines.selectionOutlines,
      },
    }
    const floorSelectables: Selectable[] = element.children.map((child) => ({
      target: { type: "element", subPath: child.key },
      selectable3d: {
        hitbox: hitboxes[child.urn]?.[0],
        outlines: calculateEdgesGeometry(hitboxes[child.urn]?.[0]),
      },
    }))
    return { selectionMode: "custom-selectables-only", selectables: [roofSelectable, ...floorSelectables] }
  }

  generateAreaStatsSurfaces = generateAreaStatsSurfaces

  canGenerateVolume25D = (e: FormaElement) => BasicBuildingAPI.isBasicFloor(e)

  generateVolume25D = (element: FormaElement, parent: FormaElement) => {
    if (!BasicBuildingAPI.isBasicFloor(element)) return
    const floorIndex = parent.children?.findIndex((child) => child.urn === element.urn)
    return generateVolume25DCollection((parent as BasicBuildingElement).representations.__INTERNAL__.data, floorIndex)
  }

  isSubSelectionElement = (element: FormaElement) => {
    return BasicBuildingAPI.isBasicFloor(element)
  }

  deletePaths = (deletePaths: string[], snapshot: ElementSnapshot) => {
    return BasicBuildingAPI.actions.createDeleteActions(deletePaths, snapshot)
  }

  saveHandler = async (elementsToSave: NotPersistedContainers[]): Promise<SavingResult[]> => {
    // The input URNs will include floor elements, but we only want to save the building elements.
    // Also note that as of writing (2024-08-09) it's not possible to getElement a single floor,
    // only the building itself.

    const buildingContainers = elementsToSave
      .filter(({ urn }) => BasicBuildingAPI.isBasicBuildingUrn(urn))
      .map(({ container }) => container)

    const body = buildingContainers.map((container) => {
      const element = container.element
      const { id, revision } = parseUrn(container.element.urn)
      const building = (element as BasicBuildingElement).representations.__INTERNAL__.data
      return { id, revision, building }
    })

    try {
      const response = await request(`/api/basicbuilding/elements-batch?authcontext=${PROJECT_ID}&newRepresentations`, {
        method: "PUT",
        body: gzip(JSON.stringify(body)),
        headers: { "Content-Type": "application/forma.basicbuilding.v3+json", "Content-Encoding": "gzip" },
      })

      // TODO: What if status is not 201? What is this check trying to achieve?
      if (response.status === 201) {
        return loadPersistedElementsAndChildren(new Set(buildingContainers.map((it) => it.element.urn)))
      }

      return []
    } catch (e) {
      return [genericSaveError(e)]
    }
  }
}
